### ISSUE TITLE
Publish on hub.docker.com

### ISSUE THREAD

**Issue by martinjuhasz** [tatoalo/torrentManager#18]
Any plans to publish this on docker hub directly?

Seems really cool, was looking excatly for that, will give it a try later on. 

I'm asking for docker hub simply because for the system i would use it for (unraid), installing from docker hub is default.

**Comment by tatoalo** [comment]
Hey @martinjuhasz! 

Thanks, happy to hear that and excited about possible feedback :)

Currently I already publish on `hub.docker.com` as well, you can access it [here](https://hub.docker.com/r/tatoalo/torrent-manager/).

**Comment by martinjuhasz** [comment]
ah ok.  search was not effective with "torrentmanager". thanks!
